# Generated by Django 5.1.1 on 2024-10-30 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tb_detector_app", "0002_prediction_location_prediction_patient_age_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(default="John Doe", max_length=100)),
                ("patient_age", models.IntegerField(default=15)),
                (
                    "patient_gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="images/")),
                ("result", models.BooleanField()),
                (
                    "treatment_status",
                    models.CharField(default="Unknown", max_length=20),
                ),
                ("confidence", models.FloatField()),
                (
                    "location",
                    models.CharField(default="Unknown Location", max_length=100),
                ),
                ("latitude", models.FloatField(default=0.0)),
                ("longitude", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
